# .streamlit/secrets.toml
[oracle]
user = "${ORACLE_USER}"   # lido de variável de ambiente
pwd  = "${ORACLE_PWD}"    # lido de variável de ambiente
host = "oracle.fiap.com.br"
port = 1521
sid  = "ORCL"
